include:
  - project: "ml-operation-platform/operations-antifraud/adt-pipeline-core"
    ref: "master"
    file:
      - "pipeline.yaml"

variables:
  PLAY_TBOT_CONFIG: true
  PLAY_GET_SECRETS: true
  PLAY_VERSION: true
  PLAY_DEFINE_DOCKER_REPO: true
  PLAY_DEFINE_HELM_REPO: true
  PLAY_SONAR_CODE_SCAN: true
  PLAY_DOCKER_LINT: true
  PLAY_CACHE: true
  PLAY_TESTS_RUN: true
  PYTEST_COVER_PERCENT: 0
  PYTHONPATH_FOR_TESTS: "${CI_PROJECT_DIR}/src"
  PLAY_BUILD_IMAGE: true
  DOCKERFILE_LOCAL: "Dockerfile"
  PLAY_DEPLOY_TEST: true
  PLAY_DEPLOY_PREVIEW: true
  PLAY_DEPLOY_PROD: true
  PLAY_RELEASE: true
  PLAY_ROLL_BACK_DEPLOY_TEST: true
  PLAY_ROLL_BACK_DEPLOY_PREVIEW: true
  PLAY_ROLL_BACK_DEPLOY_PROD: true